"SELECT  "
"CONCAT( "
"CONCAT(HEX(service_id), '_', HEX(pat_tsid), '_', HEX(orig_netid), '_EEEE0000='), "
"SET icon = CONCAT('logos/', "
"  REPLACE( "
"    REPLACE( "
"      REPLACE( "
"        REPLACE( "
"          REPLACE( "
"            REPLACE( "
"              REPLACE( "
"                REPLACE( "
"                  REPLACE( "
"                    REPLACE( "
"                      REPLACE( "
"                        REPLACE(LOWER(service_name), ' ', ''), "
"                      "'", ''), "
"                    '+', 'plus'), "
"                  '&', 'and'), "
"                '.', ''), "
"              '!', ''), "
"            'lon', ''), "
"          'ketchuptoo', 'ketchuptv'), "
"        'aljazeeraarabic', 'aljazeera'), "
"      'aljazeeraenglish', 'aljazeera'), "
"    'sonlife', 'sonlifetv'), "
"  '(uk)', '') "
") "
"FROM mythconverg.channelscan_channel "
"where scanid = (select max(scanid) from mythconverg.channelscan_channel) "
"order by logical_channel + 0 "
" "
" "