    "UPDATE channel "
    "SET "
    "  icon = CONCAT ( "
    "    'logos/', "
    "    REPLACE ( "
    "      REPLACE ( "
    "        REPLACE ( "
    "          REPLACE ( "
    "            REPLACE ( "
    "              REPLACE ( "
    "                REPLACE ( "
    "                  REPLACE ( "
    "                    REPLACE ( "
    "                      REPLACE ( "
    "                        REPLACE (REPLACE (LOWER(name), ' ', ''), \"'\", ''), "
    "                        '+', "
    "                        'plus' "
    "                      ), "
    "                      '&', "
    "                      'and' "
    "                    ), "
    "                    '.', "
    "                    '' "
    "                  ), "
    "                  '!', "
    "                  '' "
    "                ), "
    "                'lon', "
    "                '' "
    "              ), "
    "              'ketchuptoo', "
    "              'ketchuptv' "
    "            ), "
    "            'aljazeeraarabic', "
    "            'aljazeera' "
    "          ), "
    "          'aljazeeraenglish', "
    "          'aljazeera' "
    "        ), "
    "        'sonlife', "
    "        'sonlifetv' "
    "      ), "
    "      '(uk)', "
    "      '' "
    "    ) "
    "  ) "
    "WHERE "
    "  deleted IS NULL "